title = "nm-exp-active-netrics"
description = "Configuration file for NetMicroscope - Netrics active measurements"
topic = "default"

deployment_json_url = "https://chicago-cdac.github.io/nm-exp-active-netrics/conf/netrics.json"
# Uncomment to set a particular deployment, leave it unset and netrics will choose a 
# deployment randomly 

#deployment = "74e655581a038ce4b7b8a939b17f7cce"

# Meta.Extended info. The infomartion provided here is injected directly into the output json "as is".
# Check nm-mgmt-cms generate_pillar function for more info on how the content of these paramneters
# are being generated.

[extended]
gitlog = "{GITLOG}"
dataver = "{DATAVER}"
debhash = "{DEBHASH}"

[cron]
netrics="""
*/5 * * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -p -d -t -b {enable_ndev} {upload} >>{log} 2>&1 
{SPEEDTEST_TIME} {speedtest_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -s -l {limit-consumption} {upload} >>{log} 2>&1 
{IPERF_TIME} {iperf_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -i {limit-consumption} {upload} >{log} 2>&1
0 0 1 * * netrics env USER=$LOGNAME /usr/local/bin/netrics -R >>{log} 2>&1
"""

[databases]
    tinydb_enable = true
    tinydb_path = "databases/"

[reference_site_dict]
    "www.google.com" = "google"
    "www.amazon.com" = "amazon"
    "www.wikipedia.org" = "wikipedia"
    "www.youtube.com" = "youtube"
    "www.facebook.com" = "facebook"
    "www.chicagotribune.com" = "tribune"
    "chicago.suntimes.com" = "suntimes"
    "cs.uchicago.edu" = "uchicago"
    "4.71.251.129" = "Chicago"
    "4.35.238.193" = "Washington_DC"
    "4.71.254.129" = "Atlanta"
    "4.34.58.1" = "Denver"
    "38.102.0.65" = "Seattle"
    "183.178.65.1" = "Hong_Kong"
    "175.45.79.73" = "Sydney"
    "196.24.45.129" = "Johannesburg"
    "41.231.21.1" = "Tunis"
    "77.67.119.129" = "Paris"
    "195.89.146.193" = "Stockholm"
    "190.98.158.1" = "Sao_Paulo"

[limit_consumption]
    measured_down = 5
    max_monthly_consumption_gb = '{max_monthly_consumption_gb}'
    max_monthly_tests = '{max_monthly_tests}'

[latency_under_load]
    targets = ["www.google.com"]

[iperf]
    #buffer_length = 10000
    targets = ["{iperf_host}:{IPERF_PORT}"]

[dns_latency]
    target = "8.8.8.8"

[encrypted_dns]
    "https://freedns.controld.com/dns-query" = "controld-unfiltered"
    "https://anycast.dns.nextdns.io/dns-query" = "nextdns"
    "https://doh.ffmuc.ne/dns-query" = "doh.ffmuc.net"
    "https://doh.crypto.sx/dns-query" = "doh-crypto-sx"
    "https://us1.dnswarden.com/dns-query" = "dnswarden-adblock-us1-doh"
    "https://unicast.uncensoreddns.org/dns-query" = "uncensoreddns-dk-ipv4"
    "https://security.cloudflare-dns.com/dns-query" = "cloudflare-security"
    "https://doh.ffmuc.net/dns-query" = "doh.ffmuc.net-2"
    "https://jp.tiar.app/dns-query" = "jp.tiar.app-doh"
    "https://dns.therifleman.name/dns-query" = "dns.therifleman.name"
    "https://doh.pub/dns-query" = "dnspod-doh"
    "https://dns10.quad9.net/dns-query" = "quad9-doh-ip4-port443-nofilter-pri"
    "https://dns.adguard.com/dns-query" = "adguard-dns-doh"
    "https://a.passcloud.xyz/dns-query" = "iqdns-doh"
    "https://doh.mullvad.net/dns-query" = "mullvad-doh"
    "https://dns12.quad9.net/dns-query" = "quad9-doh-ip4-port5053-nofilter-ecs-pri"
    "https://dns-unfiltered.adguard.com/dns-query" = "adguard-dns-unfiltered-doh"
    "https://doh-ch.blahdns.com/dns-query" = "doh-ch-blahdns"
    "https://dnsse-noads.alekberg.net/dns-query" = "sth-ads-doh-se"
    "https://nextdns-ultralow/dns-query" = "nextdns-ultralow"
    "https://fr1.dnswarden.co/dns-query" = "dnswarden-adblock-fr1-doh"
    "https://dns.cloudflare.com/dns-query" = "cloudflare"
    "https://doh.appliedprivacy.net/dns-query" = "doh.appliedprivacy.net"
    "https://dns.alidns.com/dns-query" = "alidns-doh"
    "https://helios.plan9-dns.com/dns-query" = "plan9dns-mx-doh"
    "https://us1.dnswarden.com/dns-query" = "dnswarden-uncensor-us1-doh"
    "https://dnsse.alekberg.net/dns-query" = "sth-doh-se"
    "https://doh-fi.blahdns.com/dns-query" = "doh-fi-blahdns"
    "https://dns1.ryan-palmer.com/dns-query" = "dns.ryan-palmer"
    "https://doh.cleanbrowsing.org/dns-query" = "doh-cleanbrowsing-security"
    "https://dns.digitale-gesellschaft.ch/dns-query" = "dns.digitale-gesellschaft.ch-2"
    "https://dns11.quad9.net/dns-query" = "quad9-doh-ip4-port443-filter-ecs-pri"
    "https://sg1.dnswarden.com/dns-query" = "dnswarden-adult-sg1-doh"
    "https://dns.circl.lu/dns-query" = "circl-doh"
    "https://chewbacca.meganerd.nl/dns-query" = "meganerd-doh-ipv4"
    "https://ordns.he.net/dns-query" = "he"
    "https://dns12.quad9.net/dns-query" = "quad9-doh-ip4-port443-nofilter-ecs-pri"
    "https://dns11.quad9.net/dns-query" = "quad9-doh-ip4-port5053-filter-ecs-pri"
    "https://anycast.uncensoreddns.org/dns-query" = "uncensoreddns-ipv4"
    "https://doh.libredns.gr/dns-query" = "libredns-noads"
    "https://dns.brahma.world/dns-query" = "brahma-world"
    "https://dns.switch.ch/dns-query" = "switch"
    "https://dns-doh-no-safe-search.dnsforfamily.com/dns-query" = "dnsforfamily-doh-no-safe-search"
    "https://doh.chi.ahadns.net/dns-query" = "ahadns-doh-chi"
    "https://ibksturm.synology.me/dns-query" = "doh-ibksturm"
    "https://kronos.plan9-dns.com/dns-query" = "plan9dns-nj-doh"
    "https://dns-family.adguard.com/dns-query" = "adguard-dns-family-doh"
    "https://family.puredns.org/dns-query" = "puredns-family-doh"
    "https://freedns.controld.com/dns-query" = "controld-uncensored"
    "https://freedns.controld.com/dns-query" = "controld-block-malware"
    "https://dnsforge.de/dns-query" = "dnsforge.de"
    "https://doh.cleanbrowsing.org/dns-query" = "doh-cleanbrowsing-adult"
    "https://dns-doh.dnsforfamily.com/dns-query" = "dnsforfamily-doh"
    "https://public.dns.iij.jp/dns-query" = "iij"
    "https://fr1.dnswarden.com/dns-query" = "dnswarden-uncensor-fr1-doh"
    "https://family.cloudflare-dns.com/dns-query" = "cloudflare-family"
    "https://101.6.6.6/dns-query" = "tuna-doh-ipv4"
    "https://doh.pl.ahadns.net/dns-query" = "ahadns-doh-pl"
    "https://doh.cleanbrowsing.org/dns-query" = "doh-cleanbrowsing-family"
    "https://dns.google/dns-query" = "google"
    "https://freedns.controld.com/dns-query" = "controld-block-malware-ad"
    "https://v.dnscrypt.uk/dns-query" = "v.dnscrypt.uk-doh-ipv4"
    "https://doh.dnscrypt.uk/dns-query" = "dnscrypt.uk-doh-ipv4"
    "https://doh.safesurfer.io/dns-query" = "safesurfer-doh"
    "https://dnsnl.alekberg.net/dns-query" = "ams-doh-nl"
    "https://fr1.dnswarden.com/dns-query" = "dnswarden-adult-fr1-doh"
    "https://freedns.controld.com/dns-query" = "controld-family-friendly"
    "https://dns.digitale-gesellschaft.ch/dns-query" = "dns.digitale-gesellschaft.ch"
    "https://doh.la.ahadns.net/dns-query" = "ahadns-doh-la"
    "https://doh.tiar.app/dns-query" = "id-gmail-doh"
    "https://dns.dnshome.de/dns-query" = "dnshome-doh"
    "https://doh.sb/dns-query" = "dns.sb"
    "https://doh-2.seby.io/dns-query" = "publicarray-au2-doh"
    "https://doh.tiarap.org/dns-query" = "doh.tiarap.org"
    "https://dns.twnic.tw/dns-query" = "quad101"
    "https://ind1.dnswarden.com/dns-query" = "dnswarden-adblock-ind1-doh"
    "https://doh.ny.ahadns.net/dns-query" = "ahadns-doh-ny"
    "https://dns.njal.la/dns-query" = "njalla-doh"
    "https://doh.libredns.gr/dns-query" = "libredns"
    "https://pluton.plan9-dns.com/dns-query" = "plan9dns-fl-doh"
    "https://dns10.quad9.net/dns-query" = "quad9-doh-ip4-port5053-nofilter-pri"
    "https://us1.dnswarden.com/dns-query" = "dnswarden-adult-us1-doh"
    "https://dnsnl-noads.alekberg.net/dns-query" = "ams-ads-doh-nl"
    "https://jp.tiarap.org/dns-query" = "jp.tiarap.org"
    "https://doh.opendns.com/dns-query" = "cisco-doh"
    "https://doh.seby.io/dns-query" = "publicarray-au-doh"
    "https://dns.quad9.net/dns-query" = "quad9-doh-ip4-port443-filter-pri"
    "https://dns.digitalsize.net/dns-query" = "dns.digitalsize.net"
    "https://sg1.dnswarden.com/dns-query" = "dnswarden-adblock-sg1-doh"
    "https://sg1.dnswarden.com/dns-query" = "dnswarden-uncensor-sg1-doh"
    "https://ind1.dnswarden.com/dns-query" = "dnswarden-adult-ind1-doh"
    "https://puredns.org/dns-query" = "puredns-doh"
    "https://doh.bortzmeyer.fr/dns-query" = "bortzmeyer"
    "https://dns9.quad9.net/dns-query" = "quad9-doh-ip4-port5053-filter-pri"
    "https://doh.in.ahadns.net/dns-query" = "ahadns-doh-in"
    "https://adfree.usableprivacy.net/dns-query" = "adfree.usableprivacy.net"
    "https://dohtrial.att.net/dns-query" = "att"
    "https://doh.nl.ahadns.net/dns-query" = "ahadns-doh-nl"
    "https://doh-de.blahdns.com/dns-query" = "doh-de-blahdns"
    "https://doh-jp.blahdns.com/dns-query" = "doh-jp-blahdns"
    "https://ind1.dnswarden.com/dns-query" = "dnswarden-uncensor-ind1-doh"
    "https://adblock.doh.mullvad.net/dns-query" = "mullvad-adblock-doh"
    "https://dns1.dnscrypt.ca/dns-query" = "dnscrypt.ca-1-doh"
    "https://freedns.controld.com/dns-query" = "controld-block-malware-ad-social"
    "https://jp.tiarap.org/dns-query" = "odoh-jp.tiarap.org"
    "https://ibksturm.synology.me/dns-query" = "odoh-ibksturm"
    "https://odoh-target-noads.alekberg.net/dns-query" = "odoh-koki-noads-ams"
    "https://odoh.cloudflare-dns.com/dns-query" = "odoh-cloudflare"
    "https://odoh-target-se.alekberg.net/dns-query" = "odoh-koki-se"
    "https://odoh-target-noads-se.alekberg.net/dns-query" = "odoh-koki-noads-se"
    "https://odoh-target.alekberg.net/dns-query" = "odoh-koki-ams"
    "https://jp.tiar.app/dns-query" = "odoh-jp.tiar.app"
    "https://odoh.crypto.sx/dns-query" = "odoh-crypto-sx"
    "https://doh.tiarap.org/dns-query" = "odoh-tiarap.org"
    "https://doh.tiar.app/dns-query" = "odoh-id-gmail"
[hops_to_target]
    targets = ["www.google.com"]

[nmap_dev_scan]
    iface = "eth0"

[last_mile_latency]
    "1.1.1.1" = "Cloudflare_DNS"

[oplat]
    targets = ["abbott.cs.uchicago.edu:33317"]
