title = "nm-exp-active-netrics"
description = "Configuration file for NetMicroscope - Netrics active measurements"
topic = "default"

deployment_json_url = "https://chicago-cdac.github.io/nm-exp-active-netrics/conf/netrics.json"
# Uncomment to set a particular deployment, leave it unset and netrics will choose a 
# deployment randomly 

#deployment = "74e655581a038ce4b7b8a939b17f7cce"

# Meta.Extended info. The infomartion provided here is injected directly into the output json "as is".
# Check nm-mgmt-cms generate_pillar function for more info on how the content of these paramneters
# are being generated.

[extended]
gitlog = "{GITLOG}"
dataver = "{DATAVER}"
debhash = "{DEBHASH}"

[cron]
netrics="""
*/5 * * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -p -d -t -b {enable_ndev} {upload} >>{log} 2>&1 
{SPEEDTEST_TIME} {speedtest_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -s -l {limit-consumption} {upload} >>{log} 2>&1 
{IPERF_TIME} {iperf_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -i {limit-consumption} {upload} >{log} 2>&1
0 0 1 * * netrics env USER=$LOGNAME /usr/local/bin/netrics -R >>{log} 2>&1
"""

[databases]
    tinydb_enable = true
    tinydb_path = "databases/"

[reference_site_dict]
    "www.google.com" = "google"
    "www.amazon.com" = "amazon"
    "www.wikipedia.org" = "wikipedia"
    "www.youtube.com" = "youtube"
    "www.facebook.com" = "facebook"
    "www.chicagotribune.com" = "tribune"
    "chicago.suntimes.com" = "suntimes"
    "cs.uchicago.edu" = "uchicago"
    "4.71.251.129" = "Chicago"
    "4.35.238.193" = "Washington_DC"
    "4.71.254.129" = "Atlanta"
    "4.34.58.1" = "Denver"
    "38.102.0.65" = "Seattle"
    "183.178.65.1" = "Hong_Kong"
    "175.45.79.73" = "Sydney"
    "196.24.45.129" = "Johannesburg"
    "41.231.21.1" = "Tunis"
    "77.67.119.129" = "Paris"
    "195.89.146.193" = "Stockholm"
    "190.98.158.1" = "Sao_Paulo"

[limit_consumption]
    measured_down = 5
    max_monthly_consumption_gb = '{max_monthly_consumption_gb}'
    max_monthly_tests = '{max_monthly_tests}'

[latency_under_load]
    targets = ["www.google.com"]

[iperf]
    #buffer_length = 10000
    targets = ["{iperf_host}:{IPERF_PORT}"]

[dns_latency]
    target = "8.8.8.8"

[encrypted_dns]
    targets = ["https://dns.google/dns-query","https://dns.aa.net.uk/dns-query", "https://adfree.usableprivacy.net/dns-query",
	       "https://dns.adguard.com/dns-query","https://dns-family.adguard.com/dns-query","https://doh.in.ahadns.net/dns-query",
               "https://doh.la.ahadns.net/dns-query", "https://doh.nl.ahadns.net/dns-query", "https://dns.alidns.com/dns-query",
               "https://dnsnl.alekberg.net/dns-query", "https://dohtrial.att.net/dns-query", "https://dnses.alekberg.net/dns-query",
               "https://dns.circl.lu/dns-query", "https://doh.opendns.com/dns-query", "https://dns.cloudflare.com/dns-query",
               "https://family.cloudflare-dns.com/dns-query", "https://security.cloudflare-dns.com/dns-query", "https://odvr.nic.cz/dns-query",
               "https://dns.digitale-gesellschaft.ch/dns-query", "https://dns.digitale-gesellschaft.ch/dns-query", "https://dns1.ryan-palmer.com/dns-query", 
               "https://doh.sb/dns-query", "https://dns.therifleman.name/dns-query", "https://dns1.dnscrypt.ca/dns-query", "https://dns2.dnscrypt.ca/dns-query", 
               "https://dns-doh.dnsforfamily.com/dns-query", "https://dns-doh-no-safe-search.dnsforfamily.com/dns-query", "https://dnsforge.de/dns-query",
               "https://dns.dnshome.de/dns-query", "https://doh.pub/dns-query", "https://doh-ch.blahdns.com/dns-query", "https://doh.cleanbrowsing.org/dns-query", 
               "https://doh.crypto.sx/dns-query", "https://doh-de.blahdns.com/dns-query", "https://doh-fi.blahdns.com/dns-query", "https://ibksturm.synology.me/dns-query", 
               "https://doh-jp.blahdns.com/dns-query", "https://doh-sg.blahdns.com/dns-query", "https://doh.appliedprivacy.net/dns-query",
               "https://doh.ffmuc.net/dns-query", "https://doh.tiarap.org/dns-query", "https://ordns.he.net/dns-query", "https://doh.tiar.app/dns-query",
               "https://public.dns.iij.jp/dns-query", "https://doh.this.web.id/dns-query", "https://jp.tiar.app/dns-query", "https://jp.tiarap.org/dns-query",
               "https://doh.libredns.gr/dns-query", "https://doh.linuxsec.org/dns-query", "https://adblock.doh.mullvad.net/dns-query",
               "https://doh.chewbacca.meganerd.nl/dns-query", "https://doh.mullvad.net/dns-query", "https://dns.nextdns.io/dns-query",
               "https://dns.njal.la/dns-query", "https://doh.post-factum.tk/dns-query", "https://draco.plan9-ns2.com/dns-query",
               "https://doh.powerdns.org/dns-query", "https://doh.seby.io/dns-query", "https://doh-2.seby.io/dns-query", "https://dns.twnic.tw/dns-query",
               "https://dns9.quad9.net/dns-query", "https://dnsse.alekberg.net/dns-query", "https://dns.switch.ch/dns-query", "https://dns.t53.de/dns-query",
               "https://unicast.uncensoreddns.org/dns-query", "https://anycast.uncensoreddns.org/dns-query", "https://sg.yepdns.com/dns-query", 
               "https://doh.xfinity.com/dns-query"]

[hops_to_target]
    targets = ["www.google.com"]

[nmap_dev_scan]
    iface = "eth0"

[last_mile_latency]
    "1.1.1.1" = "Cloudflare_DNS"

[oplat]
    targets = ["abbott.cs.uchicago.edu:33317"]
