title = "nm-exp-active-netrics"
description = "Configuration file for NetMicroscope - Netrics active measurements"
topic = "default"

deployment_json_url = "https://chicago-cdac.github.io/nm-exp-active-netrics/conf/netrics.json"
# Uncomment to set a particular deployment, leave it unset and netrics will choose a 
# deployment randomly 

#deployment = "74e655581a038ce4b7b8a939b17f7cce"

# Meta.Extended info. The infomartion provided here is injected directly into the output json "as is".
# Check nm-mgmt-cms generate_pillar function for more info on how the content of these paramneters
# are being generated.

[extended]
gitlog = "{GITLOG}"
dataver = "{DATAVER}"
debhash = "{DEBHASH}"

[cron]
netrics="""
*/5 * * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -p -d -t -b {enable_ndev} {upload} >>{log} 2>&1 
{SPEEDTEST_TIME} {speedtest_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -s -l {limit-consumption} {upload} >>{log} 2>&1 
{IPERF_TIME} {iperf_hour} * * * netrics env USER=$LOGNAME /usr/local/bin/netrics -i {limit-consumption} {upload} >{log} 2>&1
0 0 1 * * netrics env USER=$LOGNAME /usr/local/bin/netrics -R >>{log} 2>&1
"""

[databases]
    tinydb_enable = true
    tinydb_path = "databases/"

[reference_site_dict]
    "www.google.com" = "google"
    "www.amazon.com" = "amazon"
    "www.wikipedia.org" = "wikipedia"
    "www.youtube.com" = "youtube"
    "www.facebook.com" = "facebook"
    "www.chicagotribune.com" = "tribune"
    "chicago.suntimes.com" = "suntimes"
    "cs.uchicago.edu" = "uchicago"
    "4.71.251.129" = "Chicago"
    "4.35.238.193" = "Washington_DC"
    "4.71.254.129" = "Atlanta"
    "4.34.58.1" = "Denver"
    "38.102.0.65" = "Seattle"
    "183.178.65.1" = "Hong_Kong"
    "175.45.79.73" = "Sydney"
    "196.24.45.129" = "Johannesburg"
    "41.231.21.1" = "Tunis"
    "77.67.119.129" = "Paris"
    "195.89.146.193" = "Stockholm"
    "190.98.158.1" = "Sao_Paulo"

[limit_consumption]
    measured_down = 5
    max_monthly_consumption_gb = '{max_monthly_consumption_gb}'
    max_monthly_tests = '{max_monthly_tests}'

[latency_under_load]
    targets = ["www.google.com"]

[iperf]
    #buffer_length = 10000
    targets = ["{iperf_host}:{IPERF_PORT}"]

[dns_latency]
    target = "8.8.8.8"

[encrypted_dns]
    "freedns.controld.com" = "controld-unfiltered"
    "anycast.dns.nextdns.io" = "nextdns"
    "doh.ffmuc.ne" = "doh.ffmuc.net"
    "doh.crypto.sx" = "doh-crypto-sx"
    "us1.dnswarden.com" = "dnswarden-adblock-us1-doh"
    "unicast.uncensoreddns.org" = "uncensoreddns-dk-ipv4"
    "security.cloudflare-dns.co" = "cloudflare-security"
    "doh.ffmuc.net" = "doh.ffmuc.net-2"
    "jp.tiar.app" = "jp.tiar.app-doh"
    "dns.therifleman.name" = "dns.therifleman.name"
    "doh.pub" = "dnspod-doh"
    "dns10.quad9.net" = "quad9-doh-ip4-port443-nofilter-pri"
    "dns.adguard.com" = "adguard-dns-doh"
    "a.passcloud.xyz" = "iqdns-doh"
    "doh.mullvad.net" = "mullvad-doh"
    "dns12.quad9.net" = "quad9-doh-ip4-port5053-nofilter-ecs-pri"
    "dns-unfiltered.adguard.com" = "adguard-dns-unfiltered-doh"
    "doh-ch.blahdns.com" = "doh-ch-blahdns"
    "dnsse-noads.alekberg.net" = "sth-ads-doh-se"
    "nextdns-ultralow" = "nextdns-ultralow"
    "fr1.dnswarden.co" = "dnswarden-adblock-fr1-doh"
    "dns.cloudflare.com" = "cloudflare"
    "doh.appliedprivacy.net" = "doh.appliedprivacy.net"
    "dns.alidns.com" = "alidns-doh"
    "helios.plan9-dns.com" = "plan9dns-mx-doh"
    "us1.dnswarden.com" = "dnswarden-uncensor-us1-doh"
    "dnsse.alekberg.net" = "sth-doh-se"
    "doh-fi.blahdns.com" = "doh-fi-blahdns"
    "dns1.ryan-palmer.com" = "dns.ryan-palmer"
    "doh.cleanbrowsing.org" = "doh-cleanbrowsing-security"
    "dns.digitale-gesellschaft.ch" = "dns.digitale-gesellschaft.ch-2"
    "dns11.quad9.ne" = "quad9-doh-ip4-port443-filter-ecs-pri"
    "sg1.dnswarden.com" = "dnswarden-adult-sg1-doh"
    "dns.circl.lu" = "circl-doh"
    "chewbacca.meganerd.nl" = "meganerd-doh-ipv4"
    "ordns.he.net" = "he"
    "dns12.quad9.net" = "quad9-doh-ip4-port443-nofilter-ecs-pri"
    "dns11.quad9.net" = "quad9-doh-ip4-port5053-filter-ecs-pri"
    "anycast.uncensoreddns.org" = "uncensoreddns-ipv4"
    "doh.libredns.gr" = "libredns-noads"
    "dns.brahma.world" = "brahma-world"
    "dns.switch.ch" = "switch"
    "dns-doh-no-safe-search.dnsforfamily.com" = "dnsforfamily-doh-no-safe-search"
    "doh.chi.ahadns.net" = "ahadns-doh-chi"
    "ibksturm.synology.me" = "doh-ibksturm"
    "kronos.plan9-dns.com" = "plan9dns-nj-doh"
    "dns-family.adguard.com" = "adguard-dns-family-doh"
    "family.puredns.org" = "puredns-family-doh"
    "freedns.controld.com" = "controld-uncensored"
    "freedns.controld.com" = "controld-block-malware"
    "dnsforge.de" = "dnsforge.de"
    "doh.cleanbrowsing.org" = "doh-cleanbrowsing-adult"
    "dns-doh.dnsforfamily.com" = "dnsforfamily-doh"
    "public.dns.iij.jp" = "iij"
    "fr1.dnswarden.com" = "dnswarden-uncensor-fr1-doh"
    "family.cloudflare-dns.com" = "cloudflare-family"
    "101.6.6.6" = "tuna-doh-ipv4"
    "doh.pl.ahadns.net" = "ahadns-doh-pl"
    "doh.cleanbrowsing.org" = "doh-cleanbrowsing-family"
    "dns.google" = "google"
    "freedns.controld.com" = "controld-block-malware-ad"
    "v.dnscrypt.uk" = "v.dnscrypt.uk-doh-ipv4"
    "doh.dnscrypt.uk" = "dnscrypt.uk-doh-ipv4"
    "doh.safesurfer.io" = "safesurfer-doh"
    "dnsnl.alekberg.net" = "ams-doh-nl"
    "fr1.dnswarden.com" = "dnswarden-adult-fr1-doh"
    "freedns.controld.com" = "controld-family-friendly"
    "dns.digitale-gesellschaft.ch" = "dns.digitale-gesellschaft.ch"
    "doh.la.ahadns.net" = "ahadns-doh-la"
    "doh.tiar.app" = "id-gmail-doh"
    "dns.dnshome.d" = "dnshome-doh"
    "doh.sb" = "dns.sb"
    "doh-2.seby.io" = "publicarray-au2-doh"
    "doh.tiarap.org" = "doh.tiarap.org"
    "dns.twnic.tw" = "quad101"
    "ind1.dnswarden.com" = "dnswarden-adblock-ind1-doh"
    "doh.ny.ahadns.net" = "ahadns-doh-ny"
    "dns.njal.la" = "njalla-doh"
    "doh.libredns.gr" = "libredns"
    "pluton.plan9-dns.com" = "plan9dns-fl-doh"
    "dns10.quad9.net" = "quad9-doh-ip4-port5053-nofilter-pri"
    "us1.dnswarden.com" = "dnswarden-adult-us1-doh"
    "dnsnl-noads.alekberg.net" = "ams-ads-doh-nl"
    "jp.tiarap.org" = "jp.tiarap.org"
    "doh.opendns.com" = "cisco-doh"
    "doh.seby.io" = "publicarray-au-doh"
    "dns.quad9.net" = "quad9-doh-ip4-port443-filter-pri"
    "dns.digitalsize.net" = "dns.digitalsize.net"
    "sg1.dnswarden.com" = "dnswarden-adblock-sg1-doh"
    "sg1.dnswarden.com" = "dnswarden-uncensor-sg1-doh"
    "ind1.dnswarden.com" = "dnswarden-adult-ind1-doh"
    "puredns.org" = "puredns-doh"
    "doh.bortzmeyer.fr" = "bortzmeyer"
    "dns9.quad9.net" = "quad9-doh-ip4-port5053-filter-pri"
    "doh.in.ahadns.net" = "ahadns-doh-in"
    "adfree.usableprivacy.net" = "adfree.usableprivacy.net"
    "dohtrial.att.net" = "att"
    "doh.nl.ahadns.net" = "ahadns-doh-nl"
    "doh-de.blahdns.com" = "doh-de-blahdns"
    "doh-jp.blahdns.com" = "doh-jp-blahdns"
    "ind1.dnswarden.com" = "dnswarden-uncensor-ind1-doh"
    "adblock.doh.mullvad.net" = "mullvad-adblock-doh"
    "dns1.dnscrypt.ca" = "dnscrypt.ca-1-doh"
    "freedns.controld.com" = "controld-block-malware-ad-social"
    "jp.tiarap.org" = "odoh-jp.tiarap.org"
    "ibksturm.synology.me" = "odoh-ibksturm"
    "odoh-target-noads.alekberg.net" = "odoh-koki-noads-ams"
    "odoh.cloudflare-dns.com" = "odoh-cloudflare"
    "odoh-target-se.alekberg.net" = "odoh-koki-se"
    "odoh-target-noads-se.alekberg.net" = "odoh-koki-noads-se"
    "odoh-target.alekberg.net" = "odoh-koki-ams"
    "jp.tiar.app" = "odoh-jp.tiar.app"
    "odoh.crypto.sx" = "odoh-crypto-sx"
    "doh.tiarap.org" = "odoh-tiarap.org"
    "doh.tiar.app" = "odoh-id-gmail"
[hops_to_target]
    targets = ["www.google.com"]

[nmap_dev_scan]
    iface = "eth0"

[last_mile_latency]
    "1.1.1.1" = "Cloudflare_DNS"

[oplat]
    targets = ["abbott.cs.uchicago.edu:33317"]
